const actionTypes = {
    LOAD_QUESTIONS_DARE: "LOAD_QUESTIONS_DARE",
    LOAD_QUESTIONS_TRUTH: "LOAD_QUESTIONS_TRUTH",
    SET_QUESTION_DARE_USED: "SET_QUESTION_DARE_USED",
    SET_QUESTION_TRUTH_USED: "SET_QUESTION_TRUTH_USED",
};

export default actionTypes